name: summoner_timer
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  json_annotation: ^4.11.0
  shared_preferences: ^2.5.4
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.13.0
  mockito: ^5.4.4
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - .env
